<?php
if (session_status() === PHP_SESSION_NONE) session_start();

if (!isset($_SESSION["user_id"]) || ($_SESSION["user_type"] ?? '') !== "admin") {
    http_response_code(403);
    echo "Forbidden";
    exit();
}

require_once __DIR__ . '/../../config/helper.php';
require_once __DIR__ . '/../../config/database.php';
require_once __DIR__ . '/../../vendor/autoload.php';

use Dompdf\Dompdf;
use Dompdf\Options;

if (!isset($db)) {
    $db = new Database();
}

$year = isset($_GET['year']) && is_numeric($_GET['year']) ? intval($_GET['year']) : null;
$filename = $year ? "CNHS_Grade_Report_{$year}.pdf" : "CNHS_All_Grade_Reports.pdf";

// Collect HTML content
ob_start();
?>

<html>

<head>
    <meta charset="utf-8">
    <style>
        @page {
            margin: 130px 40px 100px 40px;
        }

        body {
            font-family: "DejaVu Sans", Arial, Helvetica, sans-serif;
            font-size: 12px;
            color: #333;
            line-height: 1.5;
        }

        header {
            position: fixed;
            top: -110px;
            left: 0;
            right: 0;
            height: 100px;
            text-align: center;
            border-bottom: 2px solid #004080;
            padding-bottom: 10px;
        }

        header img {
            height: 65px;
            margin-bottom: 5px;
        }

        header h2 {
            font-size: 18px;
            margin: 0;
            font-weight: bold;
            color: #004080;
        }

        header h3 {
            font-size: 14px;
            margin: 4px 0;
            color: #444;
        }

        header p {
            font-size: 12px;
            color: #555;
        }

        footer {
            position: fixed;
            bottom: -70px;
            left: 0;
            right: 0;
            height: 60px;
            border-top: 1px solid #aaa;
            text-align: center;
            font-size: 10px;
            color: #555;
        }

        .page-number:after {
            content: counter(page);
        }

        main {
            margin-top: 20px;
        }

        h4 {
            color: #004080;
            margin-top: 30px;
            margin-bottom: 10px;
            border-bottom: 1px solid #004080;
            display: inline-block;
            padding-bottom: 3px;
            font-size: 13px;
        }

        table {
            border-collapse: separate;
            border-spacing: 0;
            width: 100%;
            margin: 15px 0 30px;
            border: 1px solid #ccc;
            border-radius: 6px;
            overflow: hidden;
        }

        th,
        td {
            border: 1px solid #ccc;
            padding: 6px 8px;
            text-align: center;
        }

        th {
            background-color: #f4f7fb;
            font-weight: bold;
            color: #003366;
            font-size: 11.5px;
        }

        tr:nth-child(even) td {
            background-color: #f9fbfd;
        }

        td {
            font-size: 11.5px;
        }

        .no-data {
            color: #888;
            font-style: italic;
            text-align: center;
            background: #f9f9f9;
        }

        .signature-section {
            margin-top: 80px;
            text-align: center;
        }

        .signature-line {
            display: inline-block;
            width: 200px;
            margin: 20px 30px;
            border-top: 1px solid #333;
            font-size: 11px;
            padding-top: 5px;
        }

        .summary-title {
            color: #004080;
            font-weight: bold;
            text-align: center;
            margin-top: 15px;
            font-size: 14px;
        }

        .section {
            margin-bottom: 40px;
        }
    </style>
</head>

<body>
    <header>
        <!-- Optional: Uncomment and set correct logo path -->
        <!-- <img src="path_to_logo.png" alt="School Logo"> -->
        <h2>Can-Avid National High School</h2>
        <h3>Senior High School Department</h3>
        <?php if ($year): ?>
            <p><strong>School Year:</strong> <?= htmlspecialchars($year) ?></p>
        <?php else: ?>
            <p><strong>All Yearly Summary Report</strong></p>
        <?php endif; ?>
    </header>

    <footer>
        <p>
            Generated by: <strong><?= htmlspecialchars($_SESSION['user_name'] ?? 'Administrator') ?></strong> |
            Date: <?= date('F d, Y h:i A') ?><br>
            <span class="page-number">Page </span>
        </p>
    </footer>

    <main>
        <?php
        if ($year) {
            $grades = $db->run_custom_query("
                SELECT 
                    CONCAT(students.first_name, ' ', students.last_name) AS student_name,
                    subjects.name AS subject_name,
                    grades.quarter_1, grades.quarter_2, grades.quarter_3, grades.quarter_4,
                    grades.final_grade, grades.remarks
                FROM grades
                JOIN students ON grades.student_id = students.id
                JOIN subjects ON grades.subject_id = subjects.id
                WHERE YEAR(grades.created_at) = {$year}
                ORDER BY students.last_name, students.first_name, subjects.name
            ");

            if ($grades) {
                $first_sem = [];
                $second_sem = [];

                foreach ($grades as $g) {
                    $q1 = floatval($g['quarter_1']);
                    $q2 = floatval($g['quarter_2']);
                    $q3 = floatval($g['quarter_3']);
                    $q4 = floatval($g['quarter_4']);

                    $has_first_sem = ($q1 > 0 || $q2 > 0);
                    $has_second_sem = ($q3 > 0 || $q4 > 0);

                    if ($has_first_sem) $first_sem[] = $g;
                    if ($has_second_sem) $second_sem[] = $g;
                }

                // --- FIRST SEMESTER ---
                echo "<div class='section'><h4>First Semester</h4>";
                echo "<table>
                        <thead>
                            <tr>
                                <th>Student Name</th>
                                <th>Subject</th>
                                <th>Quarter 1</th>
                                <th>Quarter 2</th>
                                <th>Computed Final Grade</th>
                                <th>Remarks</th>
                            </tr>
                        </thead><tbody>";

                if (!empty($first_sem)) {
                    foreach ($first_sem as $g) {
                        $q1 = floatval($g['quarter_1']);
                        $q2 = floatval($g['quarter_2']);
                        $vals = array_filter([$q1, $q2]);
                        $computed = count($vals) ? number_format(array_sum($vals) / count($vals), 2) : '';

                        echo "<tr>
                                <td>" . htmlspecialchars($g['student_name']) . "</td>
                                <td>" . htmlspecialchars($g['subject_name']) . "</td>
                                <td>" . ($q1 ?: '') . "</td>
                                <td>" . ($q2 ?: '') . "</td>
                                <td>{$computed}</td>
                                <td>" . htmlspecialchars($g['remarks'] ?: '') . "</td>
                              </tr>";
                    }
                } else {
                    echo "<tr><td colspan='6' class='no-data'>No records found for First Semester</td></tr>";
                }
                echo "</tbody></table></div>";

                // --- SECOND SEMESTER ---
                echo "<div class='section'><h4>Second Semester</h4>";
                echo "<table>
                        <thead>
                            <tr>
                                <th>Student Name</th>
                                <th>Subject</th>
                                <th>Quarter 3</th>
                                <th>Quarter 4</th>
                                <th>Computed Final Grade</th>
                                <th>Remarks</th>
                            </tr>
                        </thead><tbody>";

                if (!empty($second_sem)) {
                    foreach ($second_sem as $g) {
                        $q3 = floatval($g['quarter_3']);
                        $q4 = floatval($g['quarter_4']);
                        $vals = array_filter([$q3, $q4]);
                        $computed = count($vals) ? number_format(array_sum($vals) / count($vals), 2) : '';

                        echo "<tr>
                                <td>" . htmlspecialchars($g['student_name']) . "</td>
                                <td>" . htmlspecialchars($g['subject_name']) . "</td>
                                <td>" . ($q3 ?: '') . "</td>
                                <td>" . ($q4 ?: '') . "</td>
                                <td>{$computed}</td>
                                <td>" . htmlspecialchars($g['remarks'] ?: '') . "</td>
                              </tr>";
                    }
                } else {
                    echo "<tr><td colspan='6' class='no-data'>No records found for Second Semester</td></tr>";
                }
                echo "</tbody></table></div>";
            } else {
                echo "<h4>First Semester</h4>
                      <table>
                        <thead><tr>
                            <th>Student Name</th><th>Subject</th><th>Quarter 1</th><th>Quarter 2</th><th>Computed Final Grade</th><th>Remarks</th>
                        </tr></thead>
                        <tbody><tr><td colspan='6' class='no-data'>No grade records found for this year.</td></tr></tbody>
                      </table>";

                echo "<h4>Second Semester</h4>
                      <table>
                        <thead><tr>
                            <th>Student Name</th><th>Subject</th><th>Quarter 3</th><th>Quarter 4</th><th>Computed Final Grade</th><th>Remarks</th>
                        </tr></thead>
                        <tbody><tr><td colspan='6' class='no-data'>No grade records found for this year.</td></tr></tbody>
                      </table>";
            }

            // Signature section for teachers/admins
            echo "
            <div class='signature-section'>
                <div class='signature-line'>Prepared by:</div>
                <div class='signature-line'>Checked by:</div>
                <div class='signature-line'>Approved by:</div>
            </div>";
        } else {
            // --- ALL YEARLY SUMMARY ---
            echo "<h4>All Yearly Summary</h4>";
            $grades = $db->run_custom_query("
                SELECT 
                    YEAR(created_at) AS year,
                    COUNT(*) AS total_records,
                    COUNT(DISTINCT student_id) AS total_students,
                    COUNT(DISTINCT subject_id) AS total_subjects
                FROM grades
                GROUP BY YEAR(created_at)
                ORDER BY YEAR(created_at) DESC
            ");

            echo "<table>
                    <thead>
                        <tr>
                            <th>School Year</th>
                            <th>Total Students</th>
                            <th>Total Subjects</th>
                            <th>Total Records</th>
                        </tr>
                    </thead><tbody>";

            if ($grades) {
                foreach ($grades as $r) {
                    echo "<tr>
                            <td>{$r['year']}</td>
                            <td>{$r['total_students']}</td>
                            <td>{$r['total_subjects']}</td>
                            <td>{$r['total_records']}</td>
                          </tr>";
                }
            } else {
                echo "<tr><td colspan='4' class='no-data'>No data available.</td></tr>";
            }

            echo "</tbody></table>";
        }
        ?>
    </main>
</body>

</html>

<?php
$html = ob_get_clean();

// --- Initialize Dompdf ---
$options = new Options();
$options->set('isRemoteEnabled', true);
$dompdf = new Dompdf($options);
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();

// Output PDF
$dompdf->stream($filename, ["Attachment" => true]);
exit;
?>